export const colorOpts = [
  { value: "White", label: "White" },
  { value: "Black", label: "Black" },
  { value: "Gray", label: "Gray" },
  { value: "Silver", label: "Silver" },
  { value: "Blue", label: "Blue" },
  { value: "Red", label: "Red" },
  { value: "Brown", label: "Brown" },
  { value: "Green", label: "Green" },
  { value: "Orange", label: "Orange" },
  { value: "Beige", label: "Beige" },
  { value: "Purple", label: "Purple" },
  { value: "Gold", label: "Gold" },
  { value: "Yellow", label: "Yellow" },
  { value: "Pink", label: "Pink" },
  { value: "Turquoise", label: "Turquoise" },
  { value: "Maroon", label: "Maroon" },
  { value: "Navy", label: "Navy" },
  { value: "Teal", label: "Teal" },
  { value: "Burgundy", label: "Burgundy" },
  { value: "Champagne", label: "Champagne" },
  { value: "Lime", label: "Lime" },
  { value: "Cyan", label: "Cyan" },
  { value: "Indigo", label: "Indigo" },
  { value: "Magenta", label: "Magenta" },
];
